### ISSUE TITLE
knxd doesnt emerge with gentoo "Reason: Filesize does not match recorded size"

### ISSUE THREAD

**Issue by lantoeter** [knxd/knxd#116]
Hallo, 
im trying to emerge knxd with gentoo with kernel 4.1.12.
emerge -av pthsem
works 
But
emerge -av knxd 
give me some errors:
Calculating dependencies / * Digest verification failed:
 * /usr/portage/local/knxd/sys-apps/knxd/knxd-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 1402
 * Expected: 1470                                                           . done!

!!! All ebuilds that could satisfy "knxd" have been masked.
!!! One of the following masked packages is required to complete your reques
- sys-apps/knxd-9999::knxd (masked by: corruption)

what im i doing wrong?
best regards
LANToeter

**Comment by smurfix** [comment]
Hi,
>
> emerge -av knxd
> give me some errors:
> Calculating dependencies / * Digest verification failed:
>
>   * /usr/portage/local/knxd/sys-apps/knxd/knxd-9999ebuild
>   * Reason: Filesize does not match recorded size
>   * Got: 1402
>   * Expected: 1470 done!
>
> !!! All ebuilds that could satisfy "knxd" have been masked
> !!! One of the following masked packages is required to complete your
> reques
>
>   * sys-apps/knxd-9999::knxd (masked by: corruption)
>
> what im i doing wrong?
>
That's not a knxd problem, but a gentoo packaging issue.

-- 
-- Matthias Urlichs

**Comment by mike-kfed** [comment]
since the ebuilds are in the knxd repository, I guess that is a valid bug.

@lantoeter to fix this go to the portage directory where the ebuild is located, and run this command

ebuild knxd-9999.ebuild digest

and you will be fine. If I find the time, I'll check if that issue comes from the repo original files, or it's because your ebuild was modified somehow.
