### ISSUE TITLE
USB Interface with Systemd

### ISSUE THREAD

**Issue by buchi2** [knxd/knxd#120]
Can you please help me with setting up USB Interface?
The Help command gives the output "usb:[bus[:device[:config[:interface]]]]"

But how i can correctly set up the KNXD_OPTS?

When I add KNXD_OPTS="-u /tmp/eib -D -T -R -S usb:1:4:1:0:0"  and start knxd with systemctl start knxd.service I get these error:

knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2016-01-28 22:40:54 UTC; 2s ago
  Process: 23703 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
 Main PID: 23703 (code=exited, status=1/FAILURE)

Jan 28 22:40:54 raspberrypi systemd[1]: Failed to start KNX Daemon.
Jan 28 22:40:54 raspberrypi systemd[1]: Unit knxd.service entered failed state.

**Comment by smurfix** [comment]
You need a "-b" in front of the "usb:" argument.

**Comment by buchi2** [comment]
sudo knxd -u /tmp/eib -D -T -R -S -b usb:1:4:1:0:0 gives this output:

E00000029: USBLowLevelDriver: setup config: Device or resource busy
initialisation of backend 'usb:1:4:1:0:0' failed: Resource temporarily unavailable

**Comment by smurfix** [comment]
So it attempts to talk to the USB device but cannot, probably because something else already has it open.

Most common cause: the device got a different device number than last time. Keep in mind that USB bus numbering is dynamic.

I'm sorry but somebody else will have to help you debug this further, as I don't own such an interface.
