### ISSUE TITLE
Works well, not an issue but a compliment

### ISSUE THREAD

**Issue by marcoho** [knxd/knxd#123]
Hello,
first test look really good. I have knxd with a knx - usb adapter from busware.de working together with openhab.
The aim is to do enhanced knx functionalities (like bulgary alarm) on the house linux server.

Is there a paypal account for a little donation to the project?

Cheers,
Marco

**Comment by iligiddi** [comment]
I can only agree.
It took me some time to really make it work, since required permissions were not completely described (I've added my learnings to the Wiki for others), but now KNXd is working on my Raspberry Pi 2 and 3 models with Pigator TPUART boards like a charm together with ETS5. A PI 3 with TPUART and knxd is probably one of the best KNX IP gateway solution you can get. Cost wise anyways.
Thank you so much for your efforts.

Regards
Tobias

**Comment by snowdd1** [comment]
+1 !

**Comment by KingRial** [comment]
Nice work! +1!

**Comment by smurfix** [comment]
Thanks.
