### ISSUE TITLE
How to react to group telegram

### ISSUE THREAD

**Issue by mren81** [knxd/knxd#141]
Hello, I am building my own home automation system using the KNXD command line tools (read/write). This works great. Now I want to react to group (addr.) telegrams generated by other actors (eg. switches). What is the preferred way to do this – if there is one? My first idea was to pipe the output of groupsocketlisten to a custom program, but this didn't work well (buffering). I could, of course, create a copy of groupsocketlisten replacing the printf with a web service call or whatever. However, I am not sure whether or not I approach the problem the “right” way.

Thanks in advance,
Michael

**Comment by smurfix** [comment]
On 31.05.2016 15:38, mren81 wrote:
>
> Hello, I am building my own home automation system using the KNXD
> command line tools (read/write). This works great. Now I want to react
> to group (addr.) telegrams generated by other actors (eg. switches).
> What is the preferred way to do this – if there is one? My first idea
> was to pipe the output of groupsocketlisten to a custom program, but
> this didn't work well (buffering). I could, of course, create a copy
> of groupsocketlisten replacing the printf with a web service call or
> whatever. However, I am not sure whether or not I approach the problem
> the “right” way.
>
>
No problem. Just turn off buffering of stdout. (Simple code change in
knxtool)

diff --git a/src/examples/knxtool.c b/src/examples/knxtool.c
index 5cc59d9..cf0d0fb 100644
--- a/src/examples/knxtool.c
+++ b/src/examples/knxtool.c
@@ -86,6 +86,9 @@ vbusmonitor1time\n");
          return 0;
     }
 
+  /* Buffering stdout is almost never what we want */
+  setvbuf(stdout, NULL, _IOLBF, 0);
+
   if (strcmp (prog, "on") == 0)
     {
       if (ac != 3)


This will be in git / next version shortly.

-- 
-- Matthias Urlichs

**Comment by mren81** [comment]
Thanks for the quick support. Nice to know that I am not on a completely misleading path.
Great support!

Michael

**Comment by smurfix** [comment]
On 31.05.2016 16:50, mren81 wrote:
>
> Thanks for the quick support. Nice to know that I am not on a
> completely misleading path.
> Great support!
>
You're welcome.

Issues to keep in mind:

* you need to answer reasonably quickly; groupread+response isn't meant
for delays longer than some fractions of a second.

* If your design requires regular polling of A by B, you're better off
with configuring A to do regular groupwrites. groupread+response is
meant for initializing state, after restarting B.

-- 
-- Matthias Urlichs

**Comment by chewy21** [comment]
Hello,

I'm not sure to be in the good section or if it's good to reopen a closed issue... But my question remain, so the situation is : 
on a raspberry 1 512 i have a "fully" functional knxd working the last master. I say "fully" because there is still thing to make working (like ets5 but not a real issues for now) but from the command line a can make work : writing functions, reading functions (through cache, great functions by the way), and i can read the knx frames with vbusmonitors functions. But to have a perfect behaviour of my interface i would like to have a kinda buffer or a message from knxd or knxtool when bus is updated. 
It seems that mren81 want to do the same thing but i don't understand the solution ^^
So to be simple, in a ideal world i woud like to stack telegrams and acces it with a script or even idealy directly in node.js but this part i can manage something. Or have a sort of flag ( file ? ) to tell my script that he need to check the cache and he erase the flag or turn it down ? 
I'm still beginning with linux world so it might be a solution i ignore... 
I take any help :)

By the way i'm really impressed by the work done here ! Good job !

thank's for your time !

Benoit
