### ISSUE TITLE
ETS5 compatibility

### ISSUE THREAD

**Issue by Makki1** [knxd/knxd#2]
Currently no programming of devices is possible due to changes in the way ETS5/Falcon communicates.
This is conform with KNX-Standard but not fully supported by eibd/knxd yet.

**Comment by p3root** [comment]
@Makki1 or @timowi anybody of you has a knx ip protocol specification?? I  barely find anything about knx ip device management...

**Comment by Makki1** [comment]
Yes, I have but the right way is to ask your employer to get KNX-member or buy the specs..

**Comment by p3root** [comment]
Could anybody look at this traces (www.p3.co.at/ets-traces.tar)? Could it be a bug in ETS5? 
When you look at the traces apart that ETS5 requires lot more other stuff, the traces look the same.

**Comment by timowi** [comment]
If I got this right, ets5 uses features (of knxnet/ip?) that knxd does not support. I think we should do some development together on these issues. Just start hacking is rarely a good idea with such critical stuff.

So first step: create a plan what needs to be changed in knxd.
At a second step I want to evaluate current implementation and think about testing.
Implementation should be done after we planned how to do (and test) it.

**Comment by p3root** [comment]
Like your idea. I will review this tomorrow in an more detailed way.

**Comment by do13** [comment]
@p3root: Which ETS5 version are you using?
On my side at least (partial) programming is working properly with ETS5 and knxd. Via tpuart and tunneling protocol.
Please take a look (or provide) the ETS5.log file located in C:\Users\USERNAME\AppData\Local\KNX\ETS5\Log\

**Comment by duenengeist** [comment]
Hi,
I am using ETS 5.0.1 and programming is partly working (Phy-Address only). I can check my logs and post them...

**Comment by do13** [comment]
@duenengeist 
Can you try a newer version? Latest one is 5.0.3. Which I'am using here.
IIRC there were problems with older versions.
Also check windows firewall settings. You need exceptions for
C:\Program Files\ETS5\ETS5.exe, ETS5C.exe and ETS5N.exe
There was a bug during ETS5 setup which leads to missing firewall settings.

**Comment by duenengeist** [comment]
@do13 
I have checked the firewall and added the settings for ETS5C.exe and ETS5N.exe. Did not change the behavior. I can programm the physical adress but no application.

Since I do not (yet) have a licenced version I don't know how to get the 5.0.3 as demoversion

**Comment by p3root** [comment]
You can't get 5.0.3 as demo version. I bought the ETS5 lite version today, and will work further on this issue as soon as the dongle arrives.

**Comment by duenengeist** [comment]
Hi Patrick,

I also klicked the voucher for the lite over the weekend and ordered it.
Let's see when it arrives. If you let me know what I shall test, I am
happy to help.

Carsten

Am 12.01.2015 um 11:20 schrieb Patrik Pfaffenbauer:

**Comment by RichiH** [comment]
What voucher?

**Comment by p3root** [comment]
When you finish the knx online training you pay 60€ instead of 200€ for the ets5 lite. You just pay the e-licenser (usb stick).

**Comment by duenengeist** [comment]
Hi,

exactly. To answer the questions from the training is not to much 
challenge. With freight and taxes you send end up paying 89,25€. I have 
not yet a shipdate, there seems to be a shortage with the dongles...

Carsten

Am 12.01.2015 14:03 schrieb Patrik Pfaffenbauer:

**Comment by Makki1** [comment]
I can also test now, current ETS5 is the goal, not an outdated Demo! (though I'd wish the demo to be current..)
There are some issues in eibd/knxd but, well, maybe also in ETS5..

**Comment by Makki1** [comment]
see #6, the points have been identified a branch "knxnetip-core" created

**Comment by duenengeist** [comment]
I have installed 5.0.3(Build1020) today. So far all tests worked (programming, reading of "Geräteinfo", etc.) All this did not work before with the 5.0.1. Propably next weekend I will move my "project" from ETS4 to ETS5 to see if everything really works.

**Comment by Makki1** [comment]
AFAIK this is mainly a problem with the routing-counter which has been "weakened" in ETS5.0.3 just to satisfy "broken products" (not for or only eibd/knxd).
So I want to keep that open, it is broken in knxd (not ETS5!) and therefore it should be fixed.

**Comment by p3root** [comment]
@duenengeist my ets won't update. The first it worked, but I couldn't start it 'cause of .NET exception. Than I installed it new, and now it says "Start downloading...".

**Comment by duenengeist** [comment]
ok I see. So if there is anything thatyoulike me to test, feel free to
ask :-)
Am 27.01.2015 um 00:22 schrieb Makki1:

**Comment by duenengeist** [comment]
Hi,

this worked for me with no Problems. After I l icenced the ETS it asked
if I wanted to uodate and I let it proceed. Do you have the ETS4 on the
same PC? I heard that this may case Problems.

Maybe try to open a ticket with KNXorg...

Carsten

Am 27.01.2015 um 07:57 schrieb Patrik Pfaffenbauer:

**Comment by p3root** [comment]
@duenengeist could update it right now. But thank you ;)

**Comment by smurfix** [comment]
OK, programming with ETS5 now works with my latest commit (eff7340) – at least for some value of "work", it's somewhat unreliable.

The immediate problem was that a connection's reply packets didn't get forwarded to the multicast socket because the destination didn't match. Changing the test for this was straightforward; finding the problem was not. :-1: 

At this point there are still a couple of open issues. One is that this is still quite unreliable. I'll open tickets for the other two.

**Comment by smurfix** [comment]
*Sigh* does anybody have access to the protocol spec? I'm seeing strange ETS5 errors …

**Comment by Makki1** [comment]
On 18.05.2015 16:57, Matthias Urlichs wrote:
> /Sigh/ does anybody have access to the protocol spec? I'm seeing strange
> ETS5 errors …
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/issues/2#issuecomment-103086299>.
> 
For development: http://markstaller.de/knxstd-test.zip


-- 
Mit freundlichen Grüssen

Michael Markstaller
Softwareentwicklung & IT-Dienstleistungen

Am Birkengarten 19b
85521 Taufkirchen (Post Ottobrunn)
Tel: +49-89-21553825, Mobile: +49-179-2080789,
Tel (ElabNET): +49-8102-8951-66
USt-ID: DE293191950

**Comment by smurfix** [comment]
Thank you!

Unfortunately, that's somewhat out of date. 03.08.03 lists PID values up to 76.
ETS5 sends #83, which I'd like to know how to answer.

**Comment by KingRial** [comment]
Hi smurfix,

i have the latest KNX standard ( version 2.1 ) which describes all the KNX protocols.
Officialy I cannot share them but, if you share me a contact, we could talk about them and find the infos you need.

**Comment by smurfix** [comment]
@KingRial If you could look at your copy of 03.08.03, I'd be interested in the contents of section 2.5. My copy ends with 2.5.28 which describes PID=78.
If yours doesn't contain PID=83, would you care to officially file a bug with the knx.org people, politely asking them why the *censored* this expensive ETS5 thing of theirs does something that's not specified? 

Hmmm … on second thought, the bug _may_ be that somebody typed 0x53(=83) instead of 53, which would make perfect sense in this context – but it's still a bug that slipped through testing, assuming there was any.

**Comment by KingRial** [comment]
@smurfix: As you can imagine section 2.5 ends with PID=78; so, there is no trace for PID=83.

I'll try to officualy file a bug on knx.org but usually, it's like talking to a wall :D
If you can share me some technical data to support the ticket, they could answer.
For example: the exact request you are doing to receive an 83 as an answer from ( I'm not an expert on the argument :) ).

Problably you are right and it's just a type in the code.

**Comment by do13** [comment]
@smurfix 
I don't know the exact context. Maybe it's 4.3.33 PID_DEVICE_DESCRIPTOR (PID = 83) ??

**Comment by smurfix** [comment]
@do13 Which document are you referring to? My copy of 03.08.03 doesn't even have a 4.3 section.

@KingRial See the attached wireshark screenshot.

![ets_bug](https://cloud.githubusercontent.com/assets/236571/7722444/953679c2-fee0-11e4-8034-b15fddb1af30.png)

**Comment by KingRial** [comment]
@smurfix thanks! I'll let you know if I discover something from the official channels!

**Comment by do13** [comment]
@smurfix 
03.05.01 System Specifications Resources

**Comment by smurfix** [comment]
@do13 Great fun, two PID_* tables which have almost nothing to do with each other.
I do think however that in the context of the above request, the table from 03.08.03 applies (and so does whoever wrote the cEMI dissector), so yet another explanation of the bug is "wrong guess which interface applies to the request I'm trying to send".

**Comment by smurfix** [comment]
@KingRial If you want to share anything privately, I'm at matthias@urlichs.de

**Comment by KingRial** [comment]
@smurfix: Here is the answer from the suppor ticket:
```
Could you please indicate to me in which Object Type this PID 83 is read?
As you likely know from clause 3.1 "Assignment scheme" in Chapter 3/7/3 "Standard Identifier Tables", PIDs between 51 and 200 in standard System Interface Objects are Object Type dependent.
```

This should explain why there are different PID schemes with same values: it all depends from the object type to which the request has been sent.

**Comment by pakerfeldt** [comment]
How am I supposed to at least be able to connect to my KNX network through knxd with ETS5? The only option I have is to choose IP Tunneling in ETS5 and it's not able to find my network.

This is how I start knxd: `knxd -D -S -i --eibaddr=0.0.1 --daemon=/var/log/knxd.log --no-tunnel-client-queuing ipt:192.168.1.5` and I type in the IP in ETS5 to the machine running this (192.168.1.2) and default port 3671.

Am I missing something?

**Comment by smurfix** [comment]
No, this should work. What does "not able to find your network" mean -- does the ETS not see your interface?

**Comment by pakerfeldt** [comment]
It does not see my interface no. It seems to behave different on different machines. I have a Windows 7 installation on a PC with ethernet connection. This one automatically finds:
![knx-interface](https://cloud.githubusercontent.com/assets/195860/8881110/a79245d4-323d-11e5-9352-52c695985ace.png)

192.168.1.5 is the IP router itself. I can't connect to that since I've reached the maximum number of connections (knxd is connected). Not sure about 224.0.23.12 but that interface seems to work fine.

I manually added 192.168.1.2 (knxd). When testing that interface it says "The requested connection type is not supported".

On a Macbook where I run Windows in Parallels I can't discover any interface automatically. And adding 192.168.1.2 on this machine doesn't make a difference either. The Macbook is connected through wifi.

**Comment by smurfix** [comment]
Autodiscovery and the 224.0.23.12 link depend on workling multicast. Either your Wifi or the Parallels network integration is broken and doesn't support it: both would not be surprising in any way.

"Not supported" is not surprising since you didn't enable tunneling. Add -T (before -S) and try again.

**Comment by pakerfeldt** [comment]
Oh, thanks. The flag used to be there but after switching to knxd (from eibd) it was accidently removed.

Now it works on the PC. I assume it works on Macbook as well but can't test at the moment.

**Comment by smurfix** [comment]
Current status is that programming seems to (mostly) work; packet loss seems to be a problem. Different bug …
