### ISSUE TITLE
knxd: No autostart anymore in current rpi jessie

### ISSUE THREAD

**Issue by psx01de** [knxd/knxd#244]
After updating my raspberry the last time, knxd won't start anymore. I have tried anything including uninstalling and installing the latest version, reset my knxd-configuration, follow the hints in the wiki etc.

System: Raspbian GNU/Linux 8.0 (jessie)
Linux version 4.4.50-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #970 SMP Mon Feb 20 19:18:29 GMT 2017

/etc/knxd.conf:
`# configuration for knxd.service
KNXD_OPTS="-u /tmp/eib -u /var/run/knx -D -T -S -e 1.1.90 -E 1.1.91:8 -n mediapi -b tpuarts:/dev/ttyKNX1"`

`sudo service knxd start/stop`  hat no effect
`sudo service knxd status` returns
> â knxd.service - KNX Daemon
>    Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
>    Active: activating (auto-restart) (Result: timeout) since Do 2017-04-13 23:13:44 CEST; 5s ago
>   Process: 1008 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=killed, signal=TERM)
>  Main PID: 1008 (code=killed, signal=TERM)
> 
> Apr 13 23:13:44 mediapi systemd[1]: Failed to start KNX Daemon.
> Apr 13 23:13:44 mediapi systemd[1]: Unit knxd.service entered failed state.

Calling `sudo knxd -u /tmp/eib -u /var/run/knx -D -T -S -e 1.1.90 -E 1.1.91:8 -n mediapi -b tpuarts:/dev/ttyKNX1` works for a limited time (I think it's interrupted after some time by the autostarter)

What can I to to get it working again?

**Comment by smurfix** [comment]
Hmm. This looks like an inability to initialoze the tpuart, which usually is a result of the update re-adding the serial console and/or agetty.

Please
* observe the argument order; move the -DTS to in front of the  -b
* verify that there is no agetty running and that the kernel command line does not use the serial console
* if that doesn't help, turn on logging (-f9 -t1023 in front of the "-b tpuarts:"), restart, and put the result in a pastebin

**Comment by psx01de** [comment]
Thanks for your reply.

I've followed the three steps above. Now it seems that the knxd task keeps running but don't work either.

Log: https://pastebin.com/xHB1bw9T

**Comment by vniklas123** [comment]
Hi,
Actually I'm facing exactly the same problem. Hope for a solution

**Comment by smurfix** [comment]
Fun. Please test the current v0.14 (commit 88b5653).

**Comment by psx01de** [comment]
It's not fun, it's deep darkness in the room :))

Doesn't work but more response than last time:
https://pastebin.com/tbffB12q

**Comment by smurfix** [comment]
Did you not read the knxd.conf file, which states

```
# *** DO NOT use "-u" / "-u /run/knx" or "-i" / "-i 6720" here.
# Systemd already does that on behalf of knxd, via 'knx.socket'.

```
Please remove the `-u /var/run/knx` option, and try again.

**Comment by psx01de** [comment]
Thanks so much! I have tried anything described in config and the wiki, added and removed statements and don't have the latest comments in my config file... Now, with the new version and without -u it works!

**Comment by webmiceleo** [comment]
ETS discovered knxd interface but disconnect in restart loop  ... 

/etc/knxd.conf:
DAMEON_ARGS="--eibaddr=1.1.128 --client-addrs=1.1.129:1 -D -T -R -S -b tpuarts:/dev/ttyKNX1"

any idea ?? 

`pi@raspberrypi:~ $ systemctl status knxd.socket && systemctl status knxd.service
● knxd.socket - KNX Daemon (socket)
   Loaded: loaded (/lib/systemd/system/knxd.socket; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-18 05:45:01 GMT; 6min ago
   Listen: /var/run/knx (Stream)
           [::]:6720 (Stream)

Mar 18 05:45:01 raspberrypi systemd[1]: Listening on KNX Daemon (socket).
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-18 05:51:22 GMT; 1s ago
 Main PID: 720 (knxd)
   CGroup: /system.slice/knxd.service
           └─720 /usr/bin/knxd -e 1.1.0 -E 1.1.100:28 -D -T -R -S -b tpuarts:/dev/ttyKNX1

Mar 18 05:51:22 raspberrypi systemd[1]: Starting KNX Daemon...
Mar 18 05:51:22 raspberrypi systemd[1]: Started KNX Daemon.
pi@raspberrypi:~ $ systemctl status knxd.socket && systemctl status knxd.service
● knxd.socket - KNX Daemon (socket)
   Loaded: loaded (/lib/systemd/system/knxd.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Wed 2020-03-18 05:45:01 GMT; 6min ago
   Listen: /var/run/knx (Stream)
           [::]:6720 (Stream)

Mar 18 05:45:01 raspberrypi systemd[1]: Listening on KNX Daemon (socket).
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-03-18 05:51:25 GMT; 1s ago
  Process: 720 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
 Main PID: 720 (code=exited, status=1/FAILURE)
`

**Comment by smurfix** [comment]
No. Please turn on debugging and use `journalctl`.
Also make sure that the KNX bus is powered (red LED on the TPUART interface is on)
Also² please ask in the forum, this is (most likely) not a bug per se.
Also³ please don't attach your problem to semi-random other bug reports, much less closed ones.

Thank you.
