### ISSUE TITLE
Getting rid of pthsem

### ISSUE THREAD

**Issue by christianwicke** [knxd/knxd#29]
Getting rid of pthsem

Hello,
I want to help getting getting rid of pthsem so one day we can get knxd into Debian.
My long term goal is to get rid of all threads and have one single select-loop. 
As mid term goal, I want to remove all threads that are "in the middle". I understand that threads can help with communication to the outside world (to the bus or to clients). But the layers in between should be doable without threads.

I have a created spreadsheet with all threads: http://nimkannon.de/Overview-threads.ods
The ones I could test have stacktraces for creation and shutdown.

The first thread I looked deeper into is EMI1Layer2Interface. (EMI2 and CEMI are similar.) This threads task is to read data from the LowLevelDriver and transform it L_Data_PDU / L_Busmonitor_PDU for the upper layer. This alone could be done synchronously without threads. But there are couple specialities where I have questions to it:
- There a parameter noqueue. I don't understand the code fully. Maybe delays sending the next message to the outqueue until the last message is received. Is it like this? So the effect is that all data is buffered in the LowLevelDriver until it is fetched from the upper layer?
- There is special handling for byte 0: On 0xA0 on open()/enterBusmonitor() is done again. Is this part of the knx specification that knxd has to do this?
  There is a difference between open() and enterBusmonitor(): 
  - open waits until the sendqueue is empty, e.g. until the LowLevelDriver has send it.
  - enterBusmonitor() calls LowLevelDriver::SendReset() before it sends, sleeps a little bit and then it waits only once. So it looks like, it expects the sendqueue to be empty after calling SendReset(). 
- Is this supposed to be like this?
  Why is enterBusmonitor() sleeping after calling SendReset()?
- I looked at the method LowLevelDriver::SendReset() which is called in enterBusmonitor(). Only FT12LowLevelDriver is implementing it non empty. What is the purpose of this SendReset and why is only FT12LowLevelDriver implementing it? 

Is there any public documentation to knx that could explain some of the questions?

Thanks Christian

**Comment by timowi** [comment]
I do not think we should completely remove threads. You either re implement libpth or we will loose the flexibility knxd has know. Now every part works more or less independent of each other. With a single event loop this will not be so easy.

If pthreads is available on all target platform (I think so), we should use this. But this will change the architecture of knxd. Therefor we should not start this now.

With enterBusmonitor: It not completely implemented on all interfaces. I think it's not even possible on all interfaces. Busmonitor can be ignored for now.

**Comment by christianwicke** [comment]
Probable it's not easy to remove all threads. That's why it is my loooong term goal. But even if we only get rid of some of the threads, the transition to pthreads will be easier. And for me the code is easier to understand if there are less threads.

About ignoring Busmonitor: Do you mean we can take the code out of the emi-Classes? We can leave it in but if it doesn't work and we cannot test it, it will be just in the way if we want to change anything on the code.

**Comment by timowi** [comment]
> Probable it's not easy to remove all threads. That's why it is my loooong term goal. 

It is possible, but in my opinion it in not a good idea. We should keep threads and keep the code modular. This gives tho most possibilities for future development. Removing threads is not a good goal. 

To me it seems you see knxd just as a knx stack to access the bus. But it can do more.

Currently every class works on its own. You could create more than one backend instance for example. If you try to create one big event loop things will get much more complicated in future. Removing feature to develop some of the most used core features more easily is not the way to go.

> About ignoring Busmonitor: Do you mean we can take the code out of the emi-Classes?

No. Just keep it as it is. Knxd should be as compliant with the standard as possible.

**Comment by christianwicke** [comment]
Hello Timo,
> It is possible, but in my opinion it in not a good idea. We should keep threads 
> and keep the code modular. This gives tho most possibilities for future 
> development. Removing threads is not a good goal. 

thanks for your reply. I do disagree about the benefits of having threads, but it looks like I'm the only one that does. So I'll leave them in.

**Comment by Makki1** [comment]
I want to clarify my opinion on this point again: I think pthsem is an organisational  problem - yes!
But it is also really good so let's take this step-by-step:
- integrate it
- find better alternatives (pthread?)
Not using threads at all would be big step back IMHO

**Comment by RichiH** [comment]
With my Debian Developer hat on: Whatever you depend on needs to be in Debian as a dynamically linked library so I would _vastly_ prefer something which is in Debian (and thus presumably more standard), already.

With my CS hat on: Thread, done well, are almost always better than single-threaded.

**Comment by ekarak** [comment]
I also agree, threads are an integral part in getting a performant system
woth soft-realtime latencies. The bad thing is that you need to get your
locks in order otherwise chaos will emerge, and this possibility is
exponential to the project's complexity.  This is *precisely* the reason
why the IT world is embracing actor systems (Erlang, Akka) to scale onto
the cloud.

However, there are some points for the single-process event-loop approach
with KNXd. Given the moderate bus speed of 9600bps (=> ~1ms/byte), even
soft-realtime latency is achievable with one single process and async I/O.
This I feel is a major rewrite of the project (I tried not long ago to
write the eibd client library for node.js which is purely callback-based,
... and failed :) )

2015-01-27 22:34 GMT+02:00 Richard Hartmann <notifications@github.com>:

> With my Debian Developer hat on: Whatever you depend on needs to be in
> Debian as a dynamically linked library so I would *vastly* prefer
> something which is in Debian (and thus presumably more standard), already.
>
> With my CS hat on: Thread, done well, are almost always better than
> single-threaded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Makki1/knxd/issues/29#issuecomment-71722492>.
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by christianwicke** [comment]
I share Elias point of view, that synchronizing threads is difficult. And it is difficult to test. When I cancel knxd (with USB) with Strg-C sometimes I get a segmentation fault (something with double freeing memory I think) depending on which order the threads are destroyed. I tried to find the cause but I didn't succeed.

Michael, can you clarify about the next steps:
* Do you mean with "integrate pthsem" to statically bind it to knxd like any other C/C++-code of knxd?
* You said not using threads at all would be a too big step. And Timo and Richard think it is not a good goal at all. What about reducing them? Do we want to keep classes like layer3 or the emi-classes as threads?
* Do you want to leave the threads as they are for now (and integrate pthsem) and deal with this topic later (after 1.0), or is this something that should be worked on now?
* In case this is something for now: To what thread library do we switch? And which lock-functions? Is there a migration path in which we can migrate thread by thread with separate commits?

**Comment by tru7** [comment]
I suggest to fully merge the code of pthsem into knxd and link statically. This way provides minimal risk and efforts to reach milestone version 1.0 any time soon capable to be pushed to Debian or other distributions. For >1.0 a new thread model may be developped.

**Comment by timowi** [comment]
> I suggest to fully merge the code of pthsem into knxd and link statically.

I do not think so. This just bloats the code and makes it more confusing. A better option is to add a option to autoconf/automake to download(or take a existing file) pthsem, build it and link (static) against this. This way it does not change the code base but packaging would be easier.

**Comment by timowi** [comment]
@christianwicke 
> I share Elias point of view, that synchronizing threads is difficult. And it is difficult to test.

Thats true but it's also true for your "one big loop" implementation. The big advantage of threads is you can develop each thread completely on its own. Without you have a lot of dependencies. In the end you will get a big state machine with a lot of queues... This is much worse then threads. knxd is not just a simple knx stack. There can happen more than one communication at a time. Your may have more than one physical interface plus more than one client. And then the single thread application gets complicated. So you either get a big complicated piece of code or you reimplement pth...

> What about reducing them? Do we want to keep classes like layer3 or the emi-classes as threads?

For threads we need a new architecture. Actually pthsem is your single thread select loop approach. Just in a nice library. And that is the problem now. pthsem is cooperative multitasking. Today there are no widely used cooperative multitasking libraries. So we should switch to preemptive multitasking. For this we need a new concept... Transformation of data should be done without threads. It possible this code should be reentrant. 

This is a big task and I thin this should be done by more than one person alone. You seem two step ahead with your plans. First we should comment and document the current code. Second we should think about restructuring parts of the code. (emi/cemi, packet/data transformation seem a bit scattered - could be nice encapsulated classes) The we can talk about how the new threading/locking should look...

This is definitely after 1.0. Version 1.0 should be bcusdk-0.0.5 eibd with some fixes and cleanup.

**Comment by Makki1** [comment]
I agree with all of you - in most points.

First of all: please see myself merely as a moderator, not claiming any lead here!

Let me explain a little:
- eibd/knxd is a very rock-solid-thing for many years, no memleaks, no coredumps, no segfaults.
Again, running for years(!) and I could tell that with a few hundred "real-life" installations.
This is true with the current code & pthsem.
Thats a fact to be taken into account.
-> I don't want to break that!
So if we want to change that, there need to be really good reasons! 
"It looks better" or "nicer" isn't enough.

- Though, one of (at least my) primary goals is to get it into Debian (and others, but if we master Debian, others are easy..)
The blocking thing is indeed pthsem (anybody with google can find the discussions between RSE [GNU pth] and mkoegler [pthsem]

So, what are the options:
1) remove threads? I'm against this, threads make sense.
pth(sem) is very lightweight, portable (as the name says) and pthsem is just a useful small improvement over pth which no one besides RSE ever denied.
And it works very well.

2) get pthsem as replacement of GNU pth into Debian? Puhh.. Might be very hard, but possible if we all work together.
pthsem is a 100% drop-in replacement (even in current state!) for GNU pth, it isn't used by many projects at all (pthsem is only used by linknx AFAIK and JFM could be contacted).
We could try it?

3) Integrate pthsem into knxd locally (I dont know, if Debian likes this but it is small..)

4) Rewrite the whole code and make 100 new issues (with or without threads)

I prefer 2) or 3) - in this order.
If we choose #2 I'd create a separate repository (organization) for pthsem..

**Comment by KGuetter** [comment]
Disclaimer: I don't know the internals of knxd.
Did you consider using boost::asio? It has a portable implementation of the Proactor pattern which IMHO fits quite nicely to I/O related tasks.

**Comment by smurfix** [comment]
(3) is something Debian *really* doesn't like.
(2) should be possible, given that it's a drop-in; I just looked at the changes, seems reasonable. Also only five Debian packages require libpth, it should be easy to check that they still work.
(4) No. Please don't. We have more important issues than to destabilize the code base and rewrite everything so that it fits into an event loop's mold.

**Comment by RichiH** [comment]
On Wed, Mar 11, 2015 at 6:53 AM, Matthias Urlichs
<notifications@github.com> wrote:

> (3) is something Debian really doesn't like.

Embedded libs make sure you will not get into Debian. Period.


> (2) should be possible, given that it's a drop-in; I just looked at the changes, seems reasonable. Also only five Debian packages require libpth, it should be easy to check that they still work.

I am asking the maintainer of pth about this. Hopefully, my other
email will be CC'ed correctly.


Richard

**Comment by RichiH** [comment]
Hi Yutaka,

we want to get knxd[1], a replacement of eibd[2] into Debian.

Both knxd and eibd depend on pthsem[1] a GNU pth fork which supports semaphores.

pthsem is supposed to be a drop-in replacement of pth so it's not sure
if pthsem would make it into Debian at all as long as pth is in there.

Would you be willing to look at replacing GNU pth with pthsem?

You can find a discussion about this topic here[4].


In parallel, I am asking FTP masters if they would accept pthsem alongside pth.



Richard

[1] https://github.com/knxd/knxd
[2] https://www.auto.tuwien.ac.at/~mkoegler/index.php/eibd
[3] https://www.auto.tuwien.ac.at/~mkoegler/index.php/pth
[4] https://github.com/knxd/knxd/issues/29

**Comment by RichiH** [comment]
On Wed, Mar 11, 2015 at 8:17 AM, Richard Hartmann <richih@debian.org> wrote:

> Would you be willing to look at replacing GNU pth with pthsem?

Paul Wise suggested simply merging pthsem into pth. Of course, that
would mean reviving pth upstream, but if someone would be willing to
do that...


Richard

**Comment by smurfix** [comment]
Theer's nothing much to merge from pth itself, as development basically stopped with 2.0.7.

What's left are a bunch of patches by the distros, and to step up the version number to 2.1.

**Comment by RichiH** [comment]
On 03/11/2015 04:17 PM, Richard Hartmann wrote:
> Would you be willing to look at replacing GNU pth with pthsem?

I maintain Pth in Debian, because of GnuPG and its friends.

Pth has been unmaintained in the upstream any more.  It seems pthsem
neither.

In my opinion, Pth is mostly dead.  I think that I will orphan Pth
after Jessie.

GnuPG "modern" 2.1 is now migrated to nPth.  nPth is better software,
because it is compatible with usual libpthread in the system, while
Pth is not compatible (but replacing libpthread).

I don't look at the code of pthsem and knxd, but if I were the
developers, I'd take this opportunity to consider adopting nPth (or
standard POSIX threads).  I think that porting semaphore
implementation is rather not hard, given the condition Pth and nPth
assume cooperative threads.
--

**Comment by smurfix** [comment]
@RichiH Good point, I didn't know about nPth; we should investigate that option.

**Comment by RichiH** [comment]
@smurfix Just to make really sure, the email you are replying to is from Yutaka, the DD maintaining pth in Debian.

I will poke GitHub about proper handling of email workflows...

**Comment by tru7** [comment]
@RichiH Forgive me, I still don't understand two points here, maybe you can tell me:
1) why is it not possible to include pthsem into Debian? OK, by function it's a replacement for libpth, but as a software project it's an independent fork with a different namespace which can be installed in parallel to libpth. So it should be completely up to the developpers which library to link against. What do I miss?
2) looking at my knxd installation on Ubuntu there is no single binary with a dynamically linked pthsem. If it's possible to link statically why can't the library not just be created as an object file as port of knxd source code and linked statically. OK, it's a different build mechanism but should not need code rewriting.

**Comment by smurfix** [comment]
@tru7 Debian had, in the past, a lot of problems with providing security fixes for libraries that are embedded in some other package and linked statically. Therefore current policy is that This Must Not Happen Again. Thus, there shall be One True Version of any library in Debian, and everybody else is supposed to link to it.

Given that pthsem is (supposed to be) a drop-in replacement for pth, the easiest way forward is to rename libpthsem-2.0.8 to libpth-2.1.0 and upload that to Debian Experimental – short term. Long term, replace libpth with npth, as that has at least been maintained during the last decade or so.

**Comment by Makki1** [comment]
I understand all points, a third point is: not breaking eibd/knxd, so I ask all of you to find a good&resonable solution !

**Comment by smurfix** [comment]
To anybody wo does this (i.e. pthsem>npth replacement): Note that there are lots of semaphore up+down calls which are closely associated with the fill state of a queue. That should be encapsulated in the queue object, having these separate makes the code less readable and may hide a bug or two.

**Comment by smurfix** [comment]
I have looked at npth somewhat more closely. Basically it's a thin and mostly-undocumented layer to use pthreads as a pth replacement. The problem is that it doesn't implement most of what knxd needs. In particular, event chaining is not implemented – in fact, event *anything* is not implemented. knxd uses pth's events quite extensively.

It's probably possible to teach npth that, but the amount of work is non-trivial. Not something that's done i a weekend. Or a week.

It *may* be less effort to rewrite knxd to use pthreads directly. Fewer layers of software also tend to be easier to debug. On the other hand, there's no good way to do this incrementally. :.-/

**Comment by RichiH** [comment]
@smurfix as you just referenced this issue: Any update on pthsem and/or pthreads?

**Comment by alteholz** [comment]
pth is dead upstream, there are only 5 rdepends; pthsem arose out of pth and can be used as a replacement; there is no other thread-library that could be easily used for knxd instead

So, I don't understand why nobody uploaded pthsem yet? :-)

@smurfix: there are still embedded libraries coming into Debian, the security team just has to know about that. But you are right, it should be avoided ...

@RichiH: Did you really send an email to ftpmasters? Up to now I don't see any reason why pthsem should not be accepted ...

**Comment by smurfix** [comment]
WRT Debian: somebody needs to prepare a libpth-2.1.0 which has the extensions from pthsem and upload it to Debian Experimental. This should be coordinated with the Debian maintainer of libpth, NIIBE Yutaka <gniibe@fsij.org>.

Yes, Debian may allow embedded libraries, but not without a very good reason. We don't have a good reason, as pthsem is upwards compatible. (I hope that includes its ABI; I haven't tested that yet.)

That being said, I don't like the "dead upstream" aspect of libpth. Also, I'm rather unhappy with the amount of busy-work libpth(sem) needs to do each time a thread calls some boring blocking function like recvfrom(); I would much prefer to use pthreads, plus maybe some Actor framework on top.

**Comment by RichiH** [comment]
Can you test pthsem for ABI compat then?

As soon as we have a clear path forward, I can get to packaging...

Richard

Sent by mobile; excuse my brevity.

**Comment by tru7** [comment]
Would the license allow to use it as copied code to compile and link as object file? And could that be done reasonably?

**Comment by smurfix** [comment]
Debian does not want duplicated code in their archive, no matter how. In fact, embedding it in knxd is worse than shipping a separate pthsem library.
-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
On Fri, Jul 31, 2015 at 5:11 PM, Matthias Urlichs
<notifications@github.com> wrote:
>
> Debian does not want duplicated code in their archive, no matter how. In fact, embedding it in knxd is worse than shipping a separate pthsem library.

Correct.

**Comment by alteholz** [comment]
@tru7: fhem is GPL2+, pthsem is LGPL2.1+, so you can combine both in any way. But what problem do you want to solve with your proposal?

@smurfix, @RichiH:
~$ apt-file find /jquery\.js|grep -v "static\|html\|rdoc"|wc -l
108

Of course, some of them are just links, but at least knot-doc has one and libace-doc has even several versions.

**Comment by jsauermann** [comment]
I very much appreciate the idea of replacing **libpthsem**. From my own experience as a package maintainer I would predict that maintaining a package (in this case for the sole purpose of being able to use it in **knxd**) will, in the long run, create far more work than changing **knxd** to, say, standard pthreads and standard semaphores.

I am not too familiar with **libpthsem**, but looking at the code of **knxd**, it seems like only a handful of types and functions from **libpth** are being used in **knxd**.

A reasonable strategy could be to provide these functions in a single pair of **.h** and **.cpp** files that are built around an event queue (like a vector\<event_t \*\> thing). These files could be used instead of linking to **libpthsem** until all is working, with the option to switch back to **libpthsem** if not.

Another beneficial side effect of **pthreads** compared to yet another event library could be improved response times and simpler code.

**Comment by 3sv** [comment]
Seems like there is already an implementation for gnu pth that uses system threads as implementation that is available in debian: https://packages.debian.org/wheezy/libnpth0

So if I understand this correctly only the added functions on semaphore functionality of the thmsem fork should be reimplemented to be in knxd directly.

**Comment by smurfix** [comment]
libnpth0 implements the subset of pth that's used by gnupg. That's *way* less than knxd requires, even disregarding the semaphore part. See my comment from May 21th in this issue.

libpthsem's semaphores and queue locking and such can easily be replaced with a single event queue, probably based on libev, because all that concurrency and the heap of pth threads are essentially useless: it's not as if knx is a high-throughput application where multiple computationally-intensive threads are required to get the packets out as fast as (in)humanely possible. ;-) This part can easily accomodate the network interfaces. Even better, incrementally replacing the pth-based code with libev should be easy: just run them in different pthreads.

The other is for accessing lower-level interfaces (usb, TPUART, …) which might not lend themselves to an event-based model quite as easily, or which need a fast response while accessing them. We can cover that with pthreads, too.

This should also fix the valgrind issue. Currently valgrind is useless because it does not understand the manual stack flipping libpth performs when it's switching tasks. Dropping libpth will thus help find memory leaks. I'm sure there still are some.

**Comment by Makki1** [comment]
+1

If changing, I'd vote for well-established pthread, no other "freaky"
lib like pth/pthsem was/is..

Michael

**Comment by RichiH** [comment]
This seems to be stalled. Is there any chance for progress on this?

**Comment by smurfix** [comment]
On 19.11.2015 13:25, Richard Hartmann wrote:
>
> This seems to be stalled. Is there any chance for progress on this?
>
Yes. Though that depends on which timeframe we're talking about. :-P

I intend to work on this sometime early next year.

Feel free to beat me to it …

-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
@smurfix Reminderpoke :)

**Comment by nickvanbaelen** [comment]
@smurfix Do you have a clear action plan already after the extensive discussion on this issue? I'd love to help out on this.

**Comment by smurfix** [comment]
Hi,
>
> @smurfix <https://github.com/smurfix> Do you have a clear action plan
> already after the extensive discussion on this issue? I'd love to help
> out on this.
>
Most threads/queues are used in a rather simple way:
Thread 1 pushes to a queue, sets a notifier
Thread 2 reads from that queue and does things with the packet

(a) refactor the part in Thread 2 to (2a) a process-packet method, (2b)
a read-from-queue-and-call-that-method stub
(b) replace the push-to-queue part of Thread 1 with a call to do-things()
(c) delete (2b)

(d) refactor all socket-based read() calls to use libev++.

(e) the only parts that still needs pthsem, after doing the above, is
the low-level device drivers. Initially I thought about using pthreads
for that, but why bother? you can run each "physical" L2 interface in a
separate subprocess. Use poll() in the drivers' local main loop; use a
socket to exchange packets with the main thread. (There are no metadata
which matter at this level.)
You might use another Unix-domain socket for this, which would
ultimately mean that you could dynamically attach low-level drivers to knxd.

(abc) can be done incrementally. (d) is going to be one big change
(after which the physical L2 drivers no longer compile), as pthsem and
libev don't cooperate well (if at all) in the same process. (e) can be
done for each driver, though you'd really need the hardware to make sure
that the thing still works.

Base all of this on the conn_sep branch please.

-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
One reason: Either you merge pthsem to vanilla pthsem or no Debian package
:(

Richard

Sent by mobile; excuse my brevity.

**Comment by smurfix** [comment]
Progress is happening. I have found a way to run pthsem and libev in the same program, by slightly hacking libev (I added a "pthsem" back-end). This means that we can update things incrementally, instead of doing a heap of untestable all-or-nothing work.

The `libev` branch will contain this work. I'll probably find time to get to step 3 during the next couple of days.

    step 1: hack libev (done, if untested)
    step 2: create a pthsem task that runs the libev mainloop
    step 3: convert layer3
    step 4…n-2: convert some remaining pthsem-using piece of code to libev
    step n-1: disable the pthsem mainloop, run libev mainloop directly
    step n: remove references to pthsem, drop the private libev copy, allow any libev backend

After step n, knxd can be included in Debian or whatever other Linux distro takes your fancy.

Notes for code conversion:
The basic idea is to have no queues in knxd, except for (a) the layer3 dispatcher and (b) back-ends which may block (or require a delay) sending data. This should also make the code somewhat more approachable.
Libev++ has straightforward example code how to connect multiple events to a C++ object. The state machines in various threads' Run() methods need to be converted to explicit state variables in the associated layer2 object.
Passing some random "stop me" semaphore around, like the current code is doing, will no longer be necessary. In fact I don't see requiring any semaphores at all because after we're finished there won't be any multiple threads.

**Comment by RichiH** [comment]
Yay, thanks.

Richard

Sent by mobile; excuse my brevity.

**Comment by efuchs** [comment]
Hi,
what do you think about replace pthsem with libuv instead of libev?

**Comment by smurfix** [comment]
Two reasons why libev is a better fit IMHO, at least right now.

* it has (shallow but reasonable) C++ bindings
* I can hook it into pthsem, thus we can switch over incrementally instead of all-or-nothing, *without* requiring OS-level threads, with all the locking issues that'd imply.

The libev branch already uses libev's mainloop, with a pthsem back-end. I have also moved signal handling to libev because pthsem's signal handling lost signal events when both mainloops were running.

I am confident that this approach will work.

Layer3 is next.

**Comment by tru7** [comment]
@smurfix, can you please give short instructions on how to build branch libev after cloning knxd? My libev directory stays empty. How about updating bootstrap.sh for it?

**Comment by smurfix** [comment]
.gitmodules had has the wrong URL. Already fixed. Putting it into bootstrap is a good idea, I'll do that.

The current version, with a libev-ified L3, hits strange errors (randomly cleared pthsem event ring pointers …) on my system which I haven't figured out yet.

Right now I'm also working on the unix/TCP socket handling code (which is way more work than I thought). I expect to have something useable on the 23th or so.

**Comment by smurfix** [comment]
Progress: Errors fixed. knxd runs successfully with TPUART (libev'd), unix/inet/systemd server (also libev), and multicast (phsem). Pthsem-using code doesn't always shutdown correctly, but that's a minor issue I'm not too concerned with.

Converting multicast to libev is next on my agenda, then I'll need to refactor groupcache and management support. Both need to be disabled (which is the current default) if you build the libev branch.

I'd appreciate help with the "other" back-end modules. The tpuart code should demonstrate what needs to be done. Note that it still uses its own local input buffer, which is no longer necessary (I added small classes for wrapping stream i/o) but I wanted to get knxd up and running on that interface without yet more refactoring.

**Comment by smurfix** [comment]
tpuart has a tpuarttcp backend which you can use to talk with a "remote" interface. Thus you can use 
`while : ; do socat TCP-LISTEN:50505,reuseaddr,keepalive=30 /dev/ttyAMA0,b19200,raw,echo=0,crtscts=0,clocal=1 ; done`
on your Raspberry Pi, and do the debugging with `knxd -b tpuarttcp:your.gateway.berry:50505` on the master. It's probably a good idea to do this for the other serial interfaces.

**Comment by smurfix** [comment]
Progress: multicast and the ip:/ipt: back-ends now run on libev. Of course I found a few bugs while I was at it; most notably there is some busmonitor code lying around in eibnetserver.cpp which causes all your monitor packets to get duplicated. It also (still) duplicated layer3's work of decrementing the hop counter. Somebody might want to backport these. The parts which I have tested are valgrind-clean.

The tpuart back-end also has an important bugfix: if the hardware repeats a packet, knxd will now not also do that.

Next on my agenda is fixing the group monitor and management code, which will hopefully make ETS5 work again.

TODO: The tunneling code is untested (client as well as server). The tunnel client needs a flag to teach it not to do address mapping (i.e. it's talking to knxd instead of a dumb hardware interface). The other backends which still use pthsem need to be converted, which requires hardware that I don't have. Testers and/or co-authors wanted; the process of converting a back-end is reasonably straightforward.

**Comment by tru7** [comment]
I never suceeded in compiling the libev branch. Shoud I report in this issue or create a separate one?
for example: make[3]: *** No rule to make target 'tpuartcommon.cpp', needed by 'tpuartcommon.o'.  Stop.

**Comment by smurfix** [comment]
Am 27. Dezember 2016 19:42:08 MEZ, schrieb Othmar Truniger <notifications@github.com>:
>I never suceeded in compiling the libev branch. Shoud I report in this
>issue or create a separate one?
>for example: make[3]: *** No rule to make target 'tpuartcommon.cpp',
>needed by 'tpuartcommon.o'.  Stop.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/knxd/knxd/issues/29#issuecomment-269365456

That's my fault, will be fixed tomorrow. In the meantime edit src/backends/Makefile.am and remove the 'common'.
-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
… quick interrupt, as I added the capability to interpose filters between layer3 and a back-end. I did this in order to move the reverse address mapping from layer3 and/or the ipt: back-end to a filter, allowing us to use the ipt: driver to connect to either a hardware gateway which doesn't gate physical addresses, or a knxd running with -TS which can forward physically addressed packets.

Future filters can easily do filter datagrams, translate group addresses (you want to interconnect a building where each floor uses the same address scheme … ugh), or whatever.

Next will be to get the test script to work again. Then, the TODOs form the last update.

**Comment by tru7** [comment]
Travis build fails because it cannot find libev. So it looks like this is a new requirement when pthsem is not used anymore??

**Comment by smurfix** [comment]
Travis will show a broken build on the libev branch in any case, because the test script is still failing.
I'll look into that.

**Comment by smurfix** [comment]
TODO left:
* test script
* device management commands
* write more tests
* bcu1 AKA pei16s driver

The pei16s is marked as "very experimental" in configure.ac. While it's not that difficult to rewrite, the process is a lot of work. Thus, unless somebody shows up and tells me they're actually using this thing in production, I will drop it from the libev branch.

**Comment by Makki1** [comment]
Am 02.01.2017 um 20:01 schrieb Matthias Urlichs:
> TODO left:
> 
...
>   * bcu1 AKA pei16s driver

I vote for dropping it, I know noone actually using it, it never worked
"mature stable" anyway..

Michael

**Comment by smurfix** [comment]
Dropped (for now).

**Comment by smurfix** [comment]
Current status: hardware interfaces besides tpuart (both serial-port and serial-over-TCP) work. Multicast router and tunnel, client and server, works. Group caching has been tested though it's not yet in the test script; ditto for eibread-cgi.

Open issues:
* all other interfaces, particularly USB.
* management code. This is only used with `knxtool` but not by ETS5 or whatever. I'm therefore postponing porting that code until there's a need to do so; there are other fish to fry.

**Comment by dallmair** [comment]
@smurfix You're a genius, can't wait for this to arrive in master (or even stable)!

Since I (also) have a USB interface I'd like to offer to help drive the USB backend to stability. When the rest is mature enough to start testing USB (see #190) I could at least give it a try ;)

**Comment by smurfix** [comment]
@dallmair #190 should be fixed. Please do give it a try.

**Comment by smurfix** [comment]
The libev branch now works with USB interfaces (lightly tested).

Lots of thanks to [https://knx-user-forum.de/member/1258-tru](tru) from Uster(CH) for suppyling me with an interface to test with.

**Comment by smurfix** [comment]
Next on the agenda to test is a strange doesn't-forward-tunnelled-packets bug (testcase exists).

**Comment by smurfix** [comment]
Fixed. Remaining problem is broken forwarding of phys-addressed packets (required for ETS5) which I'll look into tomorrow. As soon as that works again I'll push 0.12.0 to master.

**Comment by smurfix** [comment]
ETS5 works with USB interfaces in tunnel mode(!). You may have to use the "single" filter.

Router mode and tpuart support are still broken (but work for non-ETS use); will look at that tomorrow. Probably.

**Comment by smurfix** [comment]
Router mode works, ETS5 tested with tpuart (serial) and USB (CEMI) adapters.
Version 0.12 tagged. Test script works.
Next step: wait for more testers to report back, then push to master.

**Comment by smurfix** [comment]
Pushed.

**Comment by RichiH** [comment]
Wait, so the whole dependency is gone? It's _just_ too late to make it into Debian testing, I fear: https://wiki.debian.org/DebianStretch#Before_the_release

**Comment by smurfix** [comment]
I know, a week late. Sorry about that …

**Comment by RichiH** [comment]
No worries, glad it's done :)

On the positive side, I don't need to rush too much and can have it
hang and dry in unstable for some time.

**Comment by 2franix** [comment]
I am starting to assess the amount of work needed to get rid of pthsem in [linknx](https://github.com/linknx/linknx/issues/28). I read this entire issue's thread and would like to thank all of you for the valuable research and investigation in moving away from pthsem. Special thank you to @smurfix for his invaluable work thus far! I am not an expert with respect to libev and GNU stuff in general, so reading from people who know what they are doing is a life-safer :)

Since I am finally considering using libev in linknx three years after knxd, I was wondering if you had any feedback regarding this replacement. You definitely did it but do you still believe it was the best fit?

Thanks all!
Cyrille

**Comment by smurfix** [comment]
Let me put it this way: there are reasonable ways to write state machines (you use libev or something else that's event-based) and there are reasonable ways to write multithreaded programs (you use posix threads). The latter is difficult in C because there's no good cancellation model except "add the read end of a pipe to your `select` statement", and I didn't want the overhead of three system calls every time I queue a message from one part of the code to another.

Frankly rewriting the code to use libev was necessary anyway because in a reasonably-designed program every procedure / method should do one thing well, not three mixed together. That's a good fit for event-based code.

Yes the rewrite was a lot of work but I managed to do it somewhat incrementally, if you dig through the knxd git archive you'll find a libev-based dispatcher for pthsem. That helped a lot.

**Comment by 2franix** [comment]
Thanks @smurfix. I'll take a closer look at your changes to better understand how to proceed with libev.
