### ISSUE TITLE
Allow large packets

### ISSUE THREAD

**Issue by J-N-K** [knxd/knxd#32]
Currently packets are limited to 64 byte length. DPT24 allows strings with greater length.

**Comment by Makki1** [comment]
I agree in the issue itself, but we have to take into account:
- most devices don't support this at all, might crash or worse
In other words: it could break existing installations.
- which devices do need/support it? no one I'm aware of.
(if one wants to send long strings, don't use KNX but IP..)
So, knxd should be able to survive >64 bytes frames, yes. And should be able to send extended frames on demand, under certain circumstances (if backend allows, compile-time parameter, new API-call?)
Please comment, the 64-byte payload limit makes sense in most cases..

**Comment by J-N-K** [comment]
As we have discussed before: I need to write long strings to my CometVisu. SH.py supports larger packets, the CV backend as well. The limit here is eibd. 
I think that most IP clients support larger packets. Maybe truncating/discarding large packets before sending to TP might help.

**Comment by Makki1** [comment]
I know, but we should take care about the other 99% not using sh.py as well :)
Extended frames on TP are also ok, theoretically..
Practically you can crash some KNXnet/IP-routers even with a wrong routing-counter (the result is a customer on the phne with the words: "since I use knxd, my house crashes..")

Don't get me wrong, I fully support this issue! 

but I want to point out: we need to take care about issues that might arise due to such a change, so it should be very careful.

**Comment by tru7** [comment]
It could be implemented together with a non-default start option for the daemon. I agree old common usage should stay the same.

**Comment by RichiH** [comment]
Maybe we can ask someone at knx.org if they are doing any testing in this direction? Bricking potentially  critical components (light in emergency situations, heating in winter, etc) is not an option.

Unless it's known-safe, a compile-time option with a large warning may be the way to go.

**Comment by ekarak** [comment]
I've sent the following email to a friend of mine working in KNX:

Hi Vassilis,

Do you know, or can you redirect me please to a technical person in KNX
that can answer that question? https://github.com/Makki1/knxd/issues/32
There seems to be concern that the new support for long string payloads
will break older KNX hardware.
Warm regards!


2015-01-30 12:30 GMT+02:00 Richard Hartmann <notifications@github.com>:

> Maybe we can ask someone at knx.org if they are doing any testing in this
> direction? Bricking potentially critical components (light in emergency
> situations, heating in winter, etc) is not an option.
>
> Unless it's known-safe, a compile-time option with a large warning may be
> the way to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Makki1/knxd/issues/32#issuecomment-72181901>.
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by StevenDeBruyne** [comment]
Several other services in KNX, like Property services and memory services would allow breaking the Frame limit of many implementations. So, it's not only DPT24 (with which I suppose you mean 24.001.)

"... might crash ... ": nope. Devices are tested on reaction of Frames exceeding their reception capabilities. At least, since several years. Indeed, very old devices may react incorrect. (They will likely not carsh, but they may cut the message for instance.) Then again, one would not be able in ETS to link a GA to it carrying such DPT with that length... 

"it could break existing installations". True, to the extend that ETS today does not yet verify the length of GOs when carried across Couplers. (Why? Cause there is no such need yet.)
--> "no one I'm aware of": Likely indeed, which confirms the above.

Note that the discussion appears to focus on TP1. KNX RF and KNX IP do not have that limitation.

One should not truncate Frames. That .. will be more difficult for the receiver to detect.

"Practically you can crash some KNXnet/IP-routers even with a wrong routing-counter"? There is no such thing like a "wrong routing counter". The encodable values are 0 to 7 and all are valid. Can you give more details on the situation???

So.
Yes.
Stacks are tested on their behaviour on receiving Frames larger than their reception capabilities.
"Applications" are tested on their behaviour receiving data larger than the expected data length or larger than the length indicated in the length field.
ETS checks the "maximal supported Frame length in the communication path between itself and the communication partner."

No.
ETS does not check yet if two devices that would send longer than the standard Frames would be able to communicate, because the matter is not relevant.

**Comment by Makki1** [comment]
Steven, thanks for the clarification ! 
Given this I habe no Problem to go ahead: branch, change it, review, merge.

**Comment by smurfix** [comment]
Can somebody provide an example "large" packet so that I might be able to implement support for these?
A knxtool mod that allows me to send them would be helpful also.

**Comment by smurfix** [comment]
Do you have a reason for closing this?

**Comment by J-N-K** [comment]
It seems I was the only one in need of it, I don‘t need it anymore and I can‘t provide any useful information. I guess it makes more sense to close here and open a new issue if someone comes across this in the future.
