### ISSUE TITLE
help wanted: Dimm group by value 

### ISSUE THREAD

**Issue by jachwe** [knxd/knxd#360]
Hello everyone,
i am very new to KNX. An electrician did the installation and left me alone with the control part. :-/
Anyways, i managed to install the knxtoll and using `knxtool groupswrite ip:127.0.0.1 2/2/11 1` i.e works fine for switching the groups on/off. I also got addresses for setting values, but `knxtool groupswrite ip:127.0.0.1 2/2/11 0.5` for example won't do anything.

Any help would be highly appreciated: How can i set values which are not 0 or 100%?

Thanks in advance,

Jewe

**Comment by smurfix** [comment]
If 2/2/11 is a group address for on/off then setting it to anything else will not work, you probably have a separate group address for that and/or you need "groupwrite" without the s so that you can send a complete byte. In any case knxtool doesn't understand floating point, so 50% is 50 not 0.5. In any case² knxtool is not the correct abstraction level for anything that's not basic debugging, you're better off with Home Assistant or OpenHAB or FHEM.

**Comment by jachwe** [comment]
Thank you very much.
 It works like a charm with FHEM now.
