### ISSUE TITLE
ETS5 programming works with USB but not IPT/N

### ISSUE THREAD

**Issue by ptorrent** [knxd/knxd#368]
Hello,

I'm trying to use ETS5 with KNXD. It's work very well on USB but not when KNX is connected in IP mode.

Here my command (tested on knxd 0.12.16:bccf6f6 and the last master branch)  
I'm trying to reset 0.2.2. device (I'm not able to configure it too)
```
knxd -t 1023  -e 0.2.155  -E 0.2.156:8 -DTS -b ipt:172.21.83.21
```

Here the logs output : https://pastebin.com/0q7hmh2f

And the USB command (this one works fine, I can reset device and upload application):
On  knxd 0.12.16:bccf6f6 
```
knxd -t 0xffff -e 15.15.250 -E 15.15.251:4 -DT --Server=:3671 -u /tmp/knxd_72 b usb:
```

Any idea ?

Thanks for your support

**Comment by ersingencturk** [comment]
same here, when connected directly to pc via USB i can program with ETS but not with knxd

**Comment by tritonblaster** [comment]
same here

**Comment by songzh96** [comment]
same here

**Comment by shacal** [comment]
Same here
Updated from 0.10.x and now from stable to unstable behaviour :(

This worked before:
KNX <-> KNX IP Tunnel <-> knxd <-> ETS

**Comment by shacal** [comment]
Found issue, **ETS5** has a bug and using **knxd** with **ini** configuration adding **single** filter fixes my issues.

```
[A.ipt]
driver = ipt
filters = single
ip-address = xxx.xxx.xxx.xxx
```

**Comment by smurfix** [comment]
That may not the ETS's fault. Most commonly it's a gateway limitation / misconfiguration, in that the gateway assigns a KNX address to the client and then replaces the physical source address incoming packets. knxd without "single" then cannot forward the replies.

This doesn't matter much for ordinary KNX messages because they're always addressed to groups, but programming via ETS uses individual addresses.
