### ISSUE TITLE
RPI3B+ KNXD stop after few seconds

### ISSUE THREAD

**Issue by Dudek89** [knxd/knxd#414]
AS You see in ETS screen i have a transmission through IP for a while, and after that it always stop.  After each restart the same situation. Of course in RPI windows the same. After transmission there is information Read failes: Connection reset by peer

What can I do to keep the connection constantly?

ABB USB/S 1.1.
Raspbian Version:July 2019
Release date:2019-07-10
Kernel version:4.19
Size: 1945 MB with all updates/upgrades

![IP przez chwilę](https://user-images.githubusercontent.com/54045428/62903413-dcc73c00-bd62-11e9-9b1c-b2a18fa34b99.PNG)

**Comment by songzh96** [comment]
I have the same problem as you, I have been trying to change various parameters.、

I changed the parameters this morning and ran for dozens of minutes. Then there was an error again.

you can try the issue 291.

**Comment by tru7** [comment]
the standard answer to this kind of problem is: don't use a USB interface to access knx bus, they are broken by design

**Comment by Dudek89** [comment]
Great but it is not an answer. If You don't want to spend money to have another gateway it is the only way. And if there are people who have it working why not to try ?

**Comment by songzh96** [comment]
-e 0.0.1 -E 0.0.2:8 -b -u/tmp/eib usb:

**Comment by Dudek89** [comment]
Song and how it is working now? Did you resolv it? 

i will try today again with something

**Comment by songzh96** [comment]
> Song and how it is working now? Did you resolv it?
> 
> i will try today again with something

look my comment 2 days ago.
my dev working fine until now.

**Comment by Dudek89** [comment]
Song in my file /etc/default/knxd
it looks like that. 
**--eibaddr=1.1.128 --client-addrs=1.1.129:8 -D -T -R -S -i --allow-forced-broadcast --listen-local=/tmp/knx -t 1023 -b usb:"**

Are You using old eibd or knxd?
I was doing eveything like here on a blog 
https://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/

**Comment by songzh96** [comment]
> Song in my file /etc/default/knxd
> it looks like that.
> **--eibaddr=1.1.128 --client-addrs=1.1.129:8 -D -T -R -S -i --allow-forced-broadcast --listen-local=/tmp/knx -t 1023 -b usb:"**
> 
> Are You using old eibd or knxd?
> I was doing eveything like here on a blog
> https://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/

yes，I have used it before。
I tried a lot of methods that didn't solve the problem of USB link.
However, I installed the native knxd and then solved the problem with the appropriate command.
How to install, please see the readme.
My cmd is "-e 0.0.1 -E 0.0.2:8 -DTS -u/tmp/eib -b usb:"
Hardware: ABB USB/S 1.1., pi 3B+
Until now my knxd is working fine.
Remember to install native usb and don't use scripts.

**Comment by Dudek89** [comment]
"See the readme" ? where?

**Comment by songzh96** [comment]
in the project index


On Debian:

# Do not use "sudo" unless told to do so.
# If "dpkg-buildpackage" complains about missing packages
# ("Unmet build dependencies"): install them
# (apt-get install …) and try that step again.
# If it wants "x | y", try to install just x; install y if that doesn't work.
# Also, if it complains about conflicting packages, remove them (duh).

# first, install build tools and dependencies
sudo apt-get install git-core build-essential

# now get the source code
git clone https://github.com/knxd/knxd.git

# now build+install knxd
cd knxd
git checkout master
dpkg-buildpackage -b -uc
# To repeat: if this step fails because of missing dependencies,
# fix them and try again! See this section's first paragraph, above.
cd ..
sudo dpkg -i knxd_*.deb knxd-tools_*.deb

# … and if you'd like to update knxd:
rm knxd*.deb
cd knxd
git pull
dpkg-buildpackage -b -uc
cd ..
sudo dpkg -i knxd_*.deb knxd-tools_*.deb
Additions for other Linux distributions are very welcome.

On MacOS or Windows, please use a Linux VM. If somebody would like to submit patches for Mac OSX or Windows, go ahead and create a pull request, but please be prepared to maintain your code.

**Comment by Dudek89** [comment]
I am a fresh noob.... It is my first time with RPI and I have a Raspbian. So it means that You made it on Debian but still....

See the readme > in the project index. 
What index?

**Comment by songzh96** [comment]
https://github.com/knxd/knxd 
Click the link
Then slide the mouse down and stop when you see Building
Then read the information below, he will teach you how to install knxd, if you encounter some problems during the installation process, please read it carefully. In fact, there are some dependent files that are not installed. You will install the missing dependencies and then compile them.
Once compiled, you can use it.
