### ISSUE TITLE
KNXD installation

### ISSUE THREAD

**Issue by ptorrent** [knxd/knxd#523]
I'm trying to install KNXD:

```
autoreconf: automake failed with exit status: 1
```

![image](https://user-images.githubusercontent.com/6083644/141287093-51e2a8ba-af3e-485c-a775-b2a379969dca.png)

What am I doing wrong... ?

BUG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead

Looks like a real science to install this soft (not my frist try...)

**Comment by ptorrent** [comment]
This procedure has never work (I think for everyone)

```
# first, install build tools and dependencies. You need git, autotools, and gcc/g++.
#: check your Linux distribution's documentation if you don't know how
# You also need a "knxd" user.

# get the source code
git clone https://github.com/knxd/knxd.git

# build+install knxd
cd knxd
git checkout main
sh bootstrap.sh
./configure 
make
make install
cd ..

# Now switch to the "knxd" user and start the daemon.
```

**Comment by ptorrent** [comment]
So I found on internet "autoreconf -fis"
Now I can execute ./configure:

![image](https://user-images.githubusercontent.com/6083644/141291523-1c61041e-1775-49f1-8dbd-569123e55608.png)

is knxd complex as an OS ?

**Comment by smurfix** [comment]
I fail to see what the problem is.

If you're using Debian, get the Debian branch. Install `build-essential` and `devscripts`, then run `debuild -b -us -uc`. Install the packages it complains about (if any), repeat. Then install the `knxd*.deb` package you just created. I just tested, and yes it works.

If you're not using Debian, then *the build instructions do work* if you install the programs which the build process requires. You probbly have some outdated tool installed. There is no `BUG.am` in knxd and I have no idea where yours comes from. The most probable cause is some other directory on your PATH which confuses autotools.

This is the knxd issue tracker. I am sorry but this is not the place for toolchain problems that obviously are not knxd's fault, and I sincerely regret that I don't have time to answer / debug them.

Some helpful hints: set your system to English before you post bug reports, and use copy+paste and github's triple-backtick quoting (or the equivalent method somewhere else) instead of screenshots.

**Comment by ptorrent** [comment]
Thanks for your answer.. I'm using debian, follow your step:

after debuild -b -us -uc:


![image](https://user-images.githubusercontent.com/6083644/141294433-d2b0512f-505b-4f60-9f14-382be00cb1e5.png)

**Comment by ptorrent** [comment]
Oh yes I see..I already open an issue about knxd_arg.. lol.

https://github.com/knxd/knxd/issues/367
