### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by bert1020** [knxd/knxd#607]
hello,我在debian上部署了knxd
部署完成之后,这个监控的路由怎么一直是5?不应该是从6开始吗?
![image](https://github.com/user-attachments/assets/11f20780-1472-4358-8317-a033f96142f0)

**Comment by bert1020** [comment]
我想在服务器上部署knxd的同时再部署一套python程序,python程序负责监控knx总线数据,并处理一些逻辑之后再往总线上发送一些指令,我可以构建出一个适合python的sdk吗? 而不是通过ip的方式连接到knxd.

**Comment by dallmair** [comment]
Google Translate:

Ask some questions
===
Hello, I deployed knxd on Debian. After the deployment, why is the monitored route always 5? Shouldn't it start from 6?

I want to deploy a python program on the server while deploying knxd. The python program is responsible for monitoring the knx bus data, processing some logic and then sending some instructions to the bus. Can I build an SDK suitable for python? Instead of connecting to knxd through IP?

**Comment by smurfix** [comment]
> After the deployment, why is the monitored route always 5? Shouldn't it start from 6?

No. The original sender had 6. remember that knxd is a router, the packets you observe did come from somewhere else.

> I want to deploy a python program on the server while deploying knxd.

Use xknx or whatever other Python library fits your needs. knxd is a router, it's ignorant of the application level by design.
